= Installation
:doctype: book

https://www.nuvolaris.io[Nuvolaris] is an easy to use and portable serverless environment.

You can install it in the following supported environments:

* xref:how-to-install-on-docker-desktop.adoc[Install on Docker Desktop].
* xref:how-to-install-on-aws-ec2.adoc[Install on a single instance on AWS EC2 Instance].
* xref:how-to-install-on-hetzner-cloud.adoc[Install on a single instance on Hetzner Cloud].
* xref:how-to-install-on-aws-eks.adoc[Install on an AWS EKS Cluster].
* xref:how-to-install-on-ubuntu.adoc[Install on a generic Ubuntu Instance], tested on AWS and Hetzner
* xref:how-to-install-on-kubernetes.adoc[Install on a Kubernetes Cluster], tested on EKS, AKS and GKE

It may work on other Docker/Kubernetes environment but it has not been tested elsewhere yet, so you mileage may vary.

More environments are on the roadmap.

If something goes wrong, here is xref:troubleshooting.adoc[what to do to report problems].

== TL;DR

If you are in a hurry, in a nutshell the instructions to install Nuvolaris in a generic Kubernetes environment that supports a load balancer and block storage (EKS, AKS, GKE) are:

* Get the name of the `<kube-context>` of the Kubernetes cluster you want to use with `kubectl config get-contexts`
* https://github.com/nuvolaris/nuvolaris/releases[Download] the Nuvolaris installer and unpack it
* Install it with  `./nuv setup --context=<kube-context> --apihost=auto`
* Use `nuv wsk property get` to show the current values of apihost and auth key
* Use your server from elsewhere configuring access with ``nuv wskprops --apihost=<apihost> --auth=<auth>``using the values show in the previous step.
* Read about https://openwhisk.apache.org/documentation.html[Apache OpenWhisk documentation] to learn development, remembering to use `nuv wsk` when you see `wsk`

= Contributions

Some contributed documentation:

* xref:set-on-windows.adoc[Set a NUV variable on Window]
