= What's New 

What's new in Nuvolaris Community 3?

We have already implemented a large part of our roadmap, integrating support for many integrated services and running it in many different environments.

Nuvolaris itself is based on a rich operator, supporting the deployment of several integrated services:

* https://redis.io[Redis], a storage service
* https://min.io[MinIO], an object storage service
* https://www.postgresql.org[Postgres] a relational database
* https://www.ferretdb.io[FerretDB] A MongoDB-compatible adapter 

Nuvolaris is coupled with a  rich and extendible CLI, `nuv`.

You can use it to install and run Nuvolaris locally on https://www.docker.com[Docker Desktop] using https://kind.sigs.k8s.io[Kind]

You can then install Nuvolaris in the following cloud providers:

* https://aws.amazon.com/eks[Amazon EKS]
* https://azure.microsoft.com/en-us/products/kubernetes-service[Azure AKS]
* https://cloud.google.com/kubernetes-engine[Google GKE]
* https://linode.com/[Akamai] (formerly Linode LKS)

You can also install it  in private clouds on servers running:

* https://www.redhat.com/en/technologies/cloud-computing/openshift[RedHat OpenShift]
* https://microk8s.io[Canonical MickoK8S]
* https://k3s.io[Rancher (now SuSE) K3S]

The CLI also supports installation directly on servers accessible with SSH.
