= Developer Guide

Welcome to Nuvolaris Developer guide. 

In this section we document <<actions>> and <<runtimes>>, and we also provide some <<reference>> documentation.

Actions (functions) are the building blocks of Nuvolaris applications.

You can write actions in a number of programming languages. 

Nuvolaris supports directly <<runtimes, this list  of programming languages>>.

There is also a link:actionloop.adoc[tutorial and a development kit]to build your own runtime for your favorite programming language.


[[actions]]
== Actions

More informations about actions:

* xref:action.adoc[Action]
* xref:webaction.adoc[Web Action]
* xref:packages.adoc[Packages]
* xref:parameters.adoc[Parameters]
* xref:annotation.adoc[Annotation]

[[runtimes]]
== Runtimes

The programming languages currently directly supported are :

* xref:nodejs.adoc[Node]
* xref:python.adoc[Python]
* xref:golang.adoc[Go]
* xref:java.adoc[Java]
* xref:php.adoc[PHP]

[[reference]]
== Reference

* xref:limits.adoc[System Limits]
* xref:naming.adoc[Naming Conventions]
* xref:actionloop.adoc[Building your runtime]
* xref:runtime.adoc[Runtimes under the hood]
