= Developer Guide

Welcome to Nuvolaris Developer guide. 

Nuvolaris is based on link:https://openwhisk.apache.org[Apache OpenWhisk] and the documentation in this section is derived for the official OpenWhisk documentation.

In this section we document xref:development-actions[actions] and xref:development-runtimes[runtimes], and we also provide some xref:development-references[reference documentation].

Actions (functions) are the building blocks of Nuvolaris applications.

You can write actions in a number of programming languages. 

Nuvolaris supports directly xref:development-runtimes[this list of programming languages]. The list is expanding over the time.

There is also a xref:actions-actionloop.adoc[tutorial and a development kit] to build your own runtime for your favorite programming language.


[[development-actions]]
== Actions

More informations about actions:

* xref:actions.adoc[Action]
* xref:parameters.adoc[Parameters]
* xref:annotations.adoc[Annotation]
* xref:webactions.adoc[Web Actions]
* xref:packages.adoc[Packages]
* xref:feeds.adoc[Feeds]

[[development-runtimes]]
== Runtimes

The programming languages currently directly supported are :

* xref:actions-nodejs.adoc[Node]
* xref:actions-python.adoc[Python]
//* xref:actions-golang.adoc[Go]
//* xref:actions-java.adoc[Java]
//* xref:actions-php.adoc[PHP]

[[development-references]]
== Reference

* xref:rest_api.adoc[Rest API]
* xref:actions-actionloop.adoc[Building your runtime]
* xref:actions-new.adoc[Runtimes under the hood]
* xref:reference.adoc[Naming and Limits]
