= Actions

The `nuv action` command is designed for managing actions, featuring the frequently utilized CRUD operations such as list, create, update, and delete. We will illustrate these operations through examples using a basic hello action. Let's assume we have the following file in current directory


.The `hello.js` script
----
function main(args) {
    return { body: "Hello" }
}
----

If we want to deploy this simple action in the package `demo` let's execute:

----
$ nuv package update demo                  
ok: updated package demo
$ nuv action update demo/hello hello.js
ok: update action demo/hello
----

Note we ensured the package exists before creating the action. 

We can actually omit the package name. In this case the package name is `default` that always exists in a namespace. However we advice to always place actions in some named package. 

[NOTE]
We used `update` but we could have used `create` if the actions does not exists, because `update` also creates the action if does not exists and `update` if it is already there. However, `creates` generates an error if an action does not exist while `update` does not, so it is practical to alwasy use `update` insteand of `create` (unless we really want an error for an existing action for some reasons).


Let's try to run the action:

----
$ nuv  invoke demo/hello
{
    "body": "Hello"
}
----


Actually, the `invoke` command does not exist, or better it just a handy shortcut for  `nuv action invoke -r`

If you try to run `nuv action invoke demo/hello` you get:

----
$ nuv action invoke demo/hello
ok: invoked /_/demo/hello with id fec047bc81ff40bc8047bc81ff10bc85
----

You may wonder where is the result. Reality is in Nuvolaris all the actions are by default asynchronous, so  what you get usually the *activation id* to retrieve the result once the action completed.

To block until the action is completed  and get the result you can either use the flat `-r` or `--result` or use `nuv invoke`

Note however we are using `nuv` to invoke an action, and this means all the requests are authenticated. You cannot invoke actions directly without a `-login` into the system before.

However you can mark an action to be public, creating it with `--web true` (see below).

If you want an action to be public you can do: 

----
$ nuv action update demo/hello hello.js --web true
ok: updated action demo/hello
$ nuv url demo/hello
https://nuvolaris.dev/api/v1/web/mirella/demo/hello
----

and you can invoke it with 

----
$ curl -sL https://nuvolaris.dev/api/v1/web/dashboard/demo/hello
Hello
----

Note that the output is only showing the value of the body field.  This is because the web actions must follow a pattern to prodce an output suitable for web output, so the output should be under the key body, and so on.  Check the section on Web Actions for more informations.

[NOTE]
Actually  `nuv url` is  a short for `nuv action get --url`. You can use `nuv action get` to retrive a more detailed description of an action in JSON format.

After `action create`, `action update` and `action get`  (and the shortcuts `invoke` and `url`) we should mention `action list` and  `action delete`.

The obviously list actions and allows to delete them:

----
$ nuv action list 
/mirella/demo/hello                                                  private nodejs:18
$ nuv action delete demo/hello
ok: deleted action demo/hello
----
