= Rules

Once we have a trigger and some actions, we can create rules for the trigger. A rule connects the trigger with an action, so if you fire the trigger, it will invoke the action. Let's see this in practice in the next listing.

[[creating-rules]]
.An example of creating a rule, triggering an event, and inspecting the logs.

<1> First of all, create a file called *alert.js*
----
function main() {
  console.log("Suspicious activity!");
  return {
    result: "Suspicious activity!",
  };
}
----

<2> Then, create a nuv action for this file
----
$ nuv action create alert alert.js  
----

<3> Now, create a trigger that we call *notifyAlert*

----
$ nuv trigger create notifyAlert
----

<4> It's all ready, we can now create our rule! 

Syntax is: "nuv rule create " + {ruleName} + " " + {triggerName} + " " + {actionName}

----
$ nuv rule create alertRule notifyAlert alert
----

<5> Our environment can now be alerted if something suspicious occurred! 

Before starting, let's open another terminal window and enable polling (with the command `nuv activation poll`) to see what happens.
----
$ nuv activation poll
Enter Ctrl-c to exit.
Polling for activation logs
----

It's time, fire the trigger!

----
$ nuv trigger fire notifyAlert                                          
ok: triggered /notifyAlert with id 86b8d33f64b845f8b8d33f64b8f5f887
----

<6> Go to see activation our open CLI with activation polling now!

----
Enter Ctrl-c to exit.
Polling for activation logs

Activation: 'alert' (dfb43932d304483db43932d304383dcf)
[
    "2024-02-20T03:15.15472494535Z stdout: Suspicious activity!"
]

----

[NOTE]
As with all the other commands, you can execute `list`, `update`, and `delete` by name.

A trigger can enable multiple rules, so firing one trigger actually activates multiple actions. 

Rules can also be enabled and disabled without removing them. As in the last example, let's try to disable the first rule and fire the trigger again to see what happens. 

<1> Disabling the rule.
<2> Firing the trigger again.
----
$ nuv rule disable alertRule    
ok: disabled rule alertRule
$ nuv trigger fire notifyAlert
ok: triggered /_/notifyAlert with id 0f4fa69d910f4c738fa69d910f9c73af
----

In the activation polling window, we can see that now any action is executed. 
Of course, we can enable the rule again with 
----
nuv rule enable alertRule  
----
