== Getting Started

Imagine we have a static website and need server logic to store contacts and validate data. This would require a server, a database and some code to glue it all together. With a serverless approach, we can just sprinkle little functions (that we call actions) on top of our static website and let Nuvolaris take care of the rest. No more setting up VMs, backend web servers, databases, etc.

In this tutorial, we will see how you can take advantage of several services which are already part of a Nuvolaris deployment and develop a contact form page for users to fill it with their emails and messages, which are then sent via email to us and stored in a database.

=== Nuvolaris CLI: Nuv

Serverless development is mostly performed on the CLI, and Nuvolaris has its tool called "nuv". It's a command line tool that allows you to
deploy (and interact with) the platform seamlessly to the cloud, locally and in custom environments.

Nuv is cross-platform and can be installed on Windows, Linux and MacOS. You can find 
it here: https://github.com/nuvolaris/nuv/releases[Nuv Releases]

=== Deploy Nuvolaris Locally

To start using Nuvolaris we can easily setup a local deployment consisting of a Kubernetes cluster and Nuvolaris. This will give us a ready-to-use serverless environment. 

We also want to enable some extra services: a Postgres database, Static content with the Minio storage and a cron scheduler. We will use them shortly to upload frontend and store the data for our app! Let's run in the terminal:

[source,bash]
----
nuv config enable --postgres --static --minio --cron
nuv setup devcluster
----

And with just that (when it finishes), we have a serverless platform (with extra services) ready to use!

== Cleaning Up

Once you are done experimenting and want to tear everything down, just run:

[source,bash]
----
nuv setup devcluster --uninstall

nuv config reset
----

This will remove Nuvolaris and the local cluster, and reset the configuration.