== Getting Started

Imagine we have a static website and need server logic to store contacts 
and validate data. This would require a server, a database and
some code to glue it all together. With a serverless approach, we can
just sprinkle little functions (that we call actions) on top of our static website and let Nuvolaris 
take care of the rest. No more setting up VMs, backend web servers, databases, etc.

=== Nuvolaris CLI: Nuv

Serverless development is mostly performed on the CLI, and Nuvolaris has its tool called "nuv". It's a command line tool that allows you to
deploy (and interact with) the platform seamlessly to the cloud, locally and in custom environments.

Nuv is cross-platform and can be installed on Windows, Linux and MacOS. You can find 
it here: https://github.com/nuvolaris/nuv/releases[Nuv Releases]

=== Deploy Nuvolaris Locally

To start using Nuvolaris we can easily setup a local deployment consisting of a Kubernetes cluster and Nuvolaris. This 
will give us a ready-to-use serverless environment. We also want to enable an extra service: a Postgres database, because we will use it later. Let's run in the terminal:

[source,bash]
----
nuv config enable --postgres
----

If it's the first time you use the nuv tool, it will ask you to download the tasks. In this case, just run:

[source,bash]
----
nuv -update
----

Then re-run the config command. This will enable the extra services.

Now just run:

[source,bash]
----
nuv setup devcluster
----

And with just that (when it finishes), we have a serverless platform ready to use!

== Cleaning Up

Once you are done experimenting and want to tear everything down, just run:

[source,bash]
----
nuv setup devcluster --uninstall
nuv config disable --postgres
----

This will remove Nuvolaris and the local cluster, and disable the Postgres database that we enabled earlier.

Check out the other tutorials to learn how to build more complex applications with Nuvolaris!