== Sending an Email

Let's add a feature that shows how the system interacts with other systems. We will set up the actions to send an email when someone uses our contact form (for both complete and incomplete submissions).

We are going to use the https://sendgrid.com[SendGrid] service to send the email.

We need to:

* create a Sendgrid account;
* get an API key in the Settings->ApiKeys menu;

In the SendGrid homepage follow the signup process, once you are create a "Sender" account and finally go on the Api Keys page (in Settings) and create one.

Then we can proceed to create a new action called `send-email.js` (in the `packages/contact` folder).

[source,javascript]
----
async function main(args) {
    let response = args.body;
    console.log("Is SendGrid API key defined? " + (args.sendgrid ? "Yes" : "No"));
    console.log("Sending email to " + args.to + " from " + args.from)
    let res = await fetch("https://api.sendgrid.com/v3/mail/send", {
        method: "POST",
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + args.sendgrid
        },
        body: JSON.stringify({
            "from": { "email": args.from },
            "subject": "[Contact Form]",
            "personalizations": [
                { "to": [{ "email": args.to }] }
            ],
            "content": [
                { "type": "text/plain", "value": args.body }
            ]
        })
    });
    console.log("Status from SendGrid request: " + res.status);
    return { body: response };
}
----

This action uses 4 parameters, the `args.sendgrid` which is the API key. The `args.from` and `args.to`, the sender and recipient, and finally `args.body` which is the content. This last one will be the body returned from the submitted action.

We've also put some logs that we can use later for debugging purposes.

Let's first set up the action:

[source,bash]
----
nuv action create contact/sendemail send-email.js -p sendgrid <your api key> -p from <your authorized sender> -p to <your destination> --web true
----

We are already setting the first 3 parameters, the last one is given in input by the submit action at every invocation.

=== Creating the Action Sequence

We have developed an action that can send an email as a standalone action, but we designed it to take the output of the submit action and return it as is. Let's create a pipeline of actions now where the output of a command is used as an input for another command.

Note that it will send emails for every submission, even for incorrect inputs, so we will know if someone is trying to use the form without providing all the information. But we will only store the fully validated data in the database. 

Let's create this pipeline, called a sequence, and then test it:

[source,bash]
----
nuv action create contact/submit-sendemail --sequence contact/submit,contact/sendemail --web true
ok: created action contact/submit-sendemail
----

Now to start using this sequence instead of using the submit action, we need to update the `web/index.html` page to invoke the new sequence.

As before let's grab the url:

[source,bash]
----
nuv url contact/submit-sendemail
<apihost>/api/v1/web/nuvolaris/contact/submit-sendemail
----

And update the `index.html`:

[source,html]
----
--- <form method="POST" action="/api/v1/web/nuvolaris/contact/submit" enctype="application/x-www-form-urlencoded">

+++ <form method="POST" action="/api/v1/web/nuvolaris/contact/" enctype="application/x-www-form-urlencoded">
----

Don't forget to re-upload the web folder with `nuv web upload web/`.

Now try to fill out the form again and press send! It will execute the sequence and you will receive the email on your email account that you used in SendGrid.

====

The tutorial introduced you to some utilities to retrieve information and to the concept of `activation`. Let's use some more commands to check out the logs and see if the email was really sent.

The easiest way to check for all the activations that happen in this app with all their logs is:

[source,bash]
----
nuv activation poll

Enter Ctrl-c to exit.
Polling for activation logs
----
This command polls continuously for log messages. If you go ahead and submit a message in the app, all the actions will show up here together with their log messages. Since we've added logs in the send-email action they will be printed here.

To also check if there are some problems with your actions, run a couple of times `nuv activation list` and check the `Status` of the activations. If you see some `developer error` or any other errors, just grab the activation ID and run `nuv logs <activation ID>`.
====
