== Creating and invoking Python actions

The process of creating Python actions is similar to that of
link:actions.md#the-basics[other actions]. The following sections guide
you through creating and invoking a single Python action, and
demonstrate how to bundle multiple Python files and third party
dependencies.

An example action Python action is simply a top-level function. For
example, create a file called `+hello.py+` with the following source
code:

[source,python]
----
def main(args):
    name = args.get("name", "stranger")
    greeting = "Hello " + name + "!"
    print(greeting)
    return {"greeting": greeting}
----

An action supports not only a JSON object but also a JSON array as a
return value.

It would be a simple example that uses an array as a return value:

[source,python]
----
def main(args):
    return ["a", "b"]
----

You can also create a sequence action with actions accepting an array
param and returning an array result.

You can easily figure out the parameters with the following example:

[source,python]
----
def main(args):
    return args
----

Python actions always consume a dictionary and produce a dictionary. The
entry method for the action is `+main+` by default but may be specified
explicitly when creating the action with the `+wsk+` CLI using
`+--main+`, as with any other action type.

You can create an OpenWhisk action called `+helloPython+` from this
function as follows:

....
wsk action create helloPython hello.py
....

The CLI automatically infers the type of the action from the source file
extension. For `+.py+` source files, the action runs using a Python 3.6
runtime.

Action invocation is the same for Python actions as it is for any other
actions:

....
wsk action invoke --result helloPython --param name World
....

[source,json]
----
  {
      "greeting": "Hello World!"
  }
----

Find out more about parameters in the link:./parameters.md[Working with
parameters] section.

== Packaging Python actions in zip files

You can package a Python action and dependent modules in a zip file. The
filename of the source file containing the entry point (e.g., `+main+`)
must be `+__main__.py+`. For example, to create an action with a helper
module called `+helper.py+`, first create an archive containing your
source files:

[source,bash]
----
zip -r helloPython.zip __main__.py helper.py
----

and then create the action:

[source,bash]
----
wsk action create helloPython --kind python:3 helloPython.zip
----

== Packaging Python actions with a virtual environment in zip files

Another way of packaging Python dependencies is using a virtual
environment (`+virtualenv+`). This allows you to link additional
packages that may be installed via
https://packaging.python.org/installing/[`+pip+`] for example. To ensure
compatibility with the OpenWhisk container, package installations inside
a virtualenv must be done in the target environment. So the docker image
`+openwhisk/python3action+` should be used to create a virtualenv
directory for your action.

As with basic zip file support, the name of the source file containing
the main entry point must be `+__main__.py+`. In addition, the
virtualenv directory must be named `+virtualenv+`. Below is an example
scenario for installing dependencies, packaging them in a virtualenv,
and creating a compatible OpenWhisk action.

[arabic]
. Given a `+requirements.txt+` file that contains the `+pip+` modules
and versions to install, run the following to install the dependencies
and create a virtualenv using a compatible Docker image:

[source,bash]
----
docker run --rm -v "$PWD:/tmp" openwhisk/python3action bash \
  -c "cd tmp && virtualenv virtualenv && source virtualenv/bin/activate && pip install -r requirements.txt"
----

[arabic, start=2]
. Archive the virtualenv directory and any additional Python files:

[source,bash]
----
zip -r helloPython.zip virtualenv __main__.py
----

[arabic, start=3]
. Create the action:

[source,bash]
----
wsk action create helloPython --kind python:3 helloPython.zip
----

== Python 3 actions

Python 3 actions are executed using Python 3.6.1. This is the default
runtime for Python actions, unless you specify the `+--kind+` flag when
creating or updating an action. The following packages are available for
use by Python actions, in addition to the Python 3.6 standard libraries.