= Configuring DNS and SSL

You can use Nuvolaris as just as a serverless engine, and use the default IP or DNS provided when provisioned your server or cluster. If you do so, only http is avaialble, and it is not secure.

If you want your server or cluster is available with a well-known internet name, you can associate the **IP address** or the "ugly" default DNS name of serveres or clusters to a DNS name of your choice, to use it also to publish the static front-end of your server.

Furthermore, once you decided for a DNS name for your server, you can enable the provisioning of an SSL certificate so you server will be accessible with `https`.

In order to configure the DNS and the SSL the steps are:

. <<ip-or-dns, retrieve the IP address or the the DNS name>> of your server or cluster
. <<register-dns, register a DNS name>> of your choice with your registration name provider
. <<configure-apihost, configure Nuvolaris>> so he knows of the DNS and SSL and can use it

[#ip-or-dns]
== Retrieving the IP address or the DNS name 

If Nuvolaris is installed in your local machine with Docker, cannot configure any DNS nor SSL, so you can proceed xref:configure-services.adoc[configuring the services].

If Nuvolaris is installed in a single server, after you xref:prereq-server.adoc[satisfied the server prerequisites] you willknow the **IP address or DNS name** of you server.

If Nuvolaris is installed in a Kubernetes cluster, after you xref:prereq-server.adoc[satisfied the server cluster] prerequisites you know either the IP address or the DNS name of the load balancer.

[#register-dns]
== Register a DNS name or wildcard

Using the address of your server or cluster, you need either to configure a DNS name your already own or https://www.icann.org/en/accredited-registrars[contact a domain name registrar] to register a new DNS name dedicated to your server or cluster.

You need at least one DNS name in a domain you control, for example `nuvolaris.example.com` that points to you IP or address.

Note that:

* If you have an IP address to your load balancer you need to configure an `A` record mapping `nuvolaris.example.com` to the IP address of your server.
* If you have a DNS name to your load balancer, you need to configure a `CNAME` record mapping `nuvolaris.example.com` to the DNS name of your server.

[NOTE]
====
If you are registering a dedicated domain name for your cluster, you are advised to register wildcard name (`*`) for every domain name in `example.com` will resolve to your server. 
====

Registering a wildcard is required to xref:update-users.adoc[get a different website for for multiple users].

[#configure-apihost]
== Configure Nuvolaris to use your DNS and and enable SSL

Once you registers a `<domain-name>` (for example `nuvolaris.example.com`) or a wildcard DNS name (for example `*.example.com`) you can communicate to the installer what is this DNS name, as it is not able to detect it automatically.

Note that if you use

----
nuv config apihost <server>
----

[#wildcard]
== DNS Wildcard

Use a wildcard for statics `*`

