= Configuring DNS and SSL

You can use Nuvolaris as just as a serverless engine, and use the default IP or DNS provided when provisioned your server or cluster. If you do so, only http is avaialble, and it is not secure.

If you want your server or cluster is available with a well-known internet name, you can associate the **IP address** or the "ugly" default DNS name of serveres or clusters to a DNS name of your choice, to use it also to publish the static front-end of your server.

Furthermore, once you decided for a DNS name for your server, you can enable the provisioning of an SSL certificate so you server will be accessible with `https`.

In order to configure the DNS and the SSL the steps are:

. <<ip-or-dns, retrieve the IP address or the the DNS name>> of your server or cluster
. register a DNS name of your choice with your registration name provider
. configure Nuvolaris so he knows of the DNS and SSL and can use it

[#ip-or-dns]
== Retrieving the IP address or the DNS name 

If Nuvolaris is installed in your local machine with Docker, cannot configure any DNS nor SSL, so you can proceed xref:configure-services.adoc[configuring the services].

If Nuvolaris is installed in a single server, after you xref:prereq-server.adoc[satisfied the server prerequisites] you willknow the **IP address or DNS name** of you server.

If Nuvolaris is installed in a Kubernetes cluster, after you xref:prereq-server.adoc[satisfied the server cluster] prerequisites you know either the IP address or the DNS name of the load balancer.

Using this address, you need either to configure a DNS name your already own or https://www.icann.org/en/accredited-registrars[contact a domain name registrar] to register a new DNS name dedicated to your server or cluster.

You have 2 options:

. register single DNS names for namespace 
. register a wildcard

[#dns]
== DNS

Get the IP of the server with:

----
nuv TODO
----

configure a record to this IP in your DNS server

----
nuv config apihost <server>
----

[#wildcard]
== DNS Wildcard

Use a wildcard for statics `*`

