= Download Installer


:base-url: github.com/nuvolaris/nuv/releases/download

You can install Nuvolaris using the Command Line Tool `nuv`.

The current version of `nuv` is: *{cur-ver}*.

You can download it for your system. It is available:

* on Microsoft Windows, 64 bit version, for Intel architecture, in Microsoft Installer `msi` format
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.msi[download Windows/Intel installer]

* on Apple Mac, for Intel and ARM architectures, in `pkg` format.
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.pkg[Download Mac/Intel Installer] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.pkg[Download Mac/Intel Mac/ARM Installer]

* on various Linux distributions, 64 bit version, for Intel and ARM architectures, in Ubuntu/Debian `deb` and (RedHat/Fedora) `rpm` format.
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.deb[Download Linux/Intel for Debian/Ubuntu] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.deb[Download Limix/ARM for Debian/Ubuntu]
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.rpm[Download Linux/Intel for RedHat/SuSE] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.rpm[ARM]

Download your version from there, then install it according the procedures of your operating system.

In all the operating systems with a graphical user interface,  you can just double clicking on the installer to install it.

== Downloads 

* Windows: 
* MacOSx: 
* Linux (Ubuntu/Debian): 
