= Download and Install `nuv` 

:base-url: github.com/nuvolaris/nuv/releases/download

You can install Nuvolaris using its Command Line Interface, `nuv`.

The current version of `nuv` is: *{cur-ver}*.

You can download it for your system. It is available for the following operating systems, architectures and formats:

* for Microsoft Windows, 64 bit version only, version 10 or greater, for Intel architecture, in Microsoft Installer `msi` format
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.msi[Download `nuv` for Windows/Intel]

* on Apple macOS,  version 12 (Monterey) or greater, for Intel and ARM architectures, in `pkg` format.
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.pkg[Download `nuv` for Mac/Intel ] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.pkg[Download `nuv` for  Mac/ARM]

* On Linux, for Ubuntu at least version 22, for Debian at least version 12 Linux, 64 bit version, in format `.deb`; for RedHat at least version 8 and for SuSE at least version 12, in `rpm` format; Available for Intel and ARM architectures, 64 bit only.
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.deb[Download `nuv` for Debian/Ubuntu] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.deb[Download `nuv` for Debian/Ubuntu]
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.rpm[Download `nuv` for RedHat/SuSE] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.rpm[Download `nuv` for RedHat/SuSE]

Download your version from this page, then install it according the procedures of your operating system.

In all the operating systems with a graphical user interface, you can just double clicking on the installer to install it.

[NOTE]
==== 
beta version is currently unsigned. Check https://www.wikihow.com/Install-Software-from-Unsigned-Developers-on-a-Mac[here for install on Mac].
====

[IMPORTANT]
====
Once installed, in the first run `nuv`` will tell to update the tasks with `nuv -update`.

Executing this command will update to the latest version of the tasks.  This command should be also executed frequently as the tasks are continuosly evolving and expanding, and `nuv` will suggest to do it at least once in a day.

You nornally just need to update the tasks but sometimes you also need to update `nuv` itself. The system will detect when it is the case and tell you what to do.
====