= Download Installer


:base-url: github.com/nuvolaris/nuv/releases/download

You can install Nuvolaris using the Command Line Tool `nuv`.

The current version of `nuv` is: *{cur-ver}*.

You can download it for your system. It is available:

* on Microsoft Windows, 64 bit version, for Intel architecture, in Microsoft Installer `msi` format
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.msi[Download Windows/Intel installer]

* on Apple Mac, for Intel and ARM architectures, in package `pkg` format.
* on various Linux distributions, 64 bit version, for Intel and ARM architecturs, in Ubuntu/Debian `deb` and (RedHat/Fedora) `rpm` format.

Download your version from there, then install it according the procedures of your operating system.

In all the operating systems with a graphical user interface,  you can just double clicking on the installer to install it.

== Downloads 

* Windows: 
* MacOSx: 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.pkg[Intel] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.pkg[ARM]
* Linux (Ubuntu/Debian): 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.deb[Intel] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.deb[ARM]
* Linux (RedHat/Fedora): 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_amd64.rpm[Intel] 
** https://{base-url}/{cur-ver}/nuv_{cur-ver}_arm64.rpm[ARM]
