= Installation

Nuvolaris can be installed in many environments, using our powerful  command line interface `nuv`. You can downloded the installer xref:download.adoc[from this page].

For **development** purposes, you can install a single node Nuvolaris deployment:

* in your xref:install-local.adoc[local machine] using xref:prereq-docker.adoc[Docker Desktop] 
* in a *single* xref:install-server.adoc[Linux Server] using the following supported environments:
** xref:prereq-k3s.adoc[SuSE K3S] 
** xref:prereq-mk8s.adoc[Ubuntu MicroK8S]

For **production** purposes, you can install a multi-node Nuvolaris deployment in any xref:install-cluster.adoc[Kubernetes Cluster] accessible with its `kubeconfig` file as long the cluster satifies xref:prereq-generic.adoc[some requirements].

We support for installing a  Kubernetes cluster ready for Nuvolaris in the following  environments:

* xref:prereq-eks.adoc[EKS in Amazon AWS] 
* xref:prereq-aks.adoc[AKS in Microsoft Azure]
* xref:prereq-gke.adoc[GKE in Google Cloud]
* xref:prereq-osh.adoc[RedHat OpenShift in supported cloud] 

If you have issues, please consult the xref:faq.adoc[FAQ] and the xref:debug.adoc[troubleshooting] page. 

You can contact us in our http://nuvolaris.discourse.group
