= Installation Overview

First please read our xref:quickstart.adoc[quick start] installation guide. Even if you are in a hurry, please read it. It is a single page and it is not too long.


Nuvolaris can be installed in many environments, using our powerful command line interface `nuv`. You can download the installer xref:download.adoc[from this page].

Once you installed `nuv`, before installing you need to:

* xref:prereq.adoc[checking the prerequisites] for the installation, and satisfy them
* xref:configure.adoc[configure] your Nuvolaris installation. 

Finally, once you have the prerequisites satisfied and your installation configured, you can install:

* in your xref:install-local.adoc[local machine]
* in a xref:install-server.adoc[Linux server]
* in a xref:install-cluster.adoc[Kubernetes cluster].

After the installation, you can change the configuration then xref:update.adoc[update the system]. 

If you have issues, please consult the xref:faq.adoc[FAQ] and the xref:debug.adoc[troubleshooting] page. 

You can also discuss this with us at our http://nuvolaris.discourse.group[online forum].
