= Installation Overview

This page provides an overview of the installation process.

== Before installation

Please ensure you have:

. xref:download.adoc[downloaded the installer]
. xref:prereq.adoc[satisfied the prerequisites] 
. xref:configure.adoc[configured your installation] 

== Core Installation

Once you have completed the preparation steps,  you can proceed with:

* a local installation in your xref:install-local.adoc[local machine]
* a single server installation in a xref:install-server.adoc[Linux server]
* a clustered installation in a xref:install-cluster.adoc[Kubernetes cluster].

> **NOTE:**  The install process will notify nuvolaris creators with the type of installation (for example: clustered or server installation), no other info will be submitted. If you want to disable the notification, you can execute the following command before the setup command:
> 
>     nuv -config DO_NOT_NOTIFY_NUVOLARIS=1

== Post installation

After the installation, you can consult the  development guide 
for informations how to reconfigure and update the system.

== Support 

If something goes wrong, you can check:

* the xref:debug.adoc[Troubleshooting] page
* our online http://nuvolaris.discourse.group[Forum]


