= Prerequisites to install Nuvolaris in an Amazon EKS Cluster

https://aws.amazon.com/eks/[Amazon EKS] is a pre-built Kubernetes cluster offered by the cloud provider https://aws.amazon.com/[Amazon Web Services].

You can create an EKS Cluster in Amazon AWS for installing using Nuvolaris using xref:download.adoc[nuv] as follows:

. install the <<install-cli, AWS CLI>>
. get <<get-credentials, Access and Secret Key>>
. <<configure, configure EKS>>
. <<provision, provision EKS>>
. optionally, retrieve the <<retrieve-lb, load balancer address>> to configure a DNS name

Once you have EKS up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the AWS CLI

Our cli `nuv` uses under the hood the https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[AWS CLI version 2], so you need to dowloand and install it https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[following those instructions].

[#get-credentials]
== Getting the Access and Secret key

:create-keys: https://repost.aws/knowledge-center/create-access-key
:eksctl-permissions: https://eksctl.io/usage/minimum-iam-policies/
 
Before starting, you need to retrieve access the AWS console and {create-keys}[create an access key and secret key],  giving the minimum required discussions as described [eksctl-permissions-]

Get the Amazon keys AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, then configure access with:

[#configure]
== Configuring Amazon EKS

---
nuv config aws
---

[#provision]
== Provisioning Amazon EKS

----
nuv cloud eks create
----

[#retrieve-lb]
== Provisioning Amazon EKS

== Additional Commands

* `nuv cloud eks delete`
* `nuv cloud eks kubeconfig`
* `nuv cloud eks lb`
