= Prerequisites to install Nuvolaris in an Azure AKS Cluster

https://aws.amazon.com/eks/[Azure AKS] is a pre-built Kubernetes cluster offered by the cloud provider https://azure.microsoft.com/[Microsoft Azure].

You can create an AKS Cluster in Microsoft Azure for installing using Nuvolaris using xref:download.adoc[nuv] as follows:

. install `az`, the <<install-cli, Azure CLI>>
. <<configure, configure AKS>>
. <<provision, provision AKS>>
. optionally, retrieve the <<retrieve-lb, load balancer address>> to configure a DNS name

Once you have AKS up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the Azure CLI

Our CLI `nuv` uses under the hood the https://learn.microsoft.com/en-us/cli/azure/[Azure CLI], so you need to dowload and install it https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[following those instructions].

Once installed, ensure it is available on the terminal executing the following command:

----
az version
----

you should receive something like this:

====
`{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}`
====

[#configure]
== Configuring Azure AKS

Before provisioning your AKS cluster you need to configure AKS with the command `nuv config aks` answering to all the questions, as in the following example:

----
$ nuv config aks
*** Please, specify AKS Name for Cluster and Resource Group and press enter.
Just press enter for default [nuvolaris]: 

*** Please, specify AKS number of worker nodes and press enter.
Just press enter for default [3]: 

*** Please, specify AKS location and press enter.
To get a list of valid values use:
  az account list-locations -o table

Just press enter for default [eastus]: 

*** Please, specify AKS virtual machine type and press enter.
To get a list of valid values use:
  az vm list-sizes --location <location> -o table
where <location> is your current location.

Just press enter for default [Standard_B4ms]: 

*** Please, specify AKS disk size in gigabyte and press enter.
Just press enter for default [50]: 

*** Please, specify AKS public SSH key in AWS and press enter.
If you already have a public SSH key provide its path here. If you do not have it, generate a key pair with the following command:
  ssh-keygen
The public key defaults to ~/.ssh/id_rsa.pub.

Just press enter for default [~/.ssh/id_rsa.pub]: 
----

[#provision]
== Provisioning Azure AKS

----
nuv cloud aks create
----

[#retrieve-lb]
== Provisioning Amazon EKS

----
nuv cloud aks lb
----

== Additional Commands

* `nuv cloud aks delete`
* `nuv cloud aks kubeconfig`
