= Provision a Linux Server in Google Cloud

You can provision a server suitable to install Nuvolaris in cloud providerhttps://cloud.google.com/gcp[Google Cloud Platform (GCP)] as follows:

. install the <<install-cli, GCloud CLI>>
. <<configure, configure GKE>>
. <<provision, provision a server>>
. retrieve the <<retrieve-ip, ip address>> to configure a DNS name

Once you have Linux server up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the GCloud CLI

Our cli `nuv` uses under the hood the https://cloud.google.com/sdk/gcloud[GCloud CLI version 2], so you need to dowload and install it https://cloud.google.com/sdk/docs/install[following those instructions].

Once installed, ensure it is available on the terminal executing the following command:

----
gcloud version
----

you should receive something like this:

====
`
Google Cloud SDK 443.0.0
beta 2023.08.11
bq 2.0.96
bundled-python3-unix 3.9.16
core 2023.08.11
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.5.5
gsutil 5.25
`
====

[#configure]
== Configuring GKE to provision a server

Before you can provision a Linux server you have to configure AWS typing the command:

----
nuv config gcloud
----
