= Prerequisites to install Nuvolaris in a Google GKE Cluster

https://cloud.google.com/kubernetes-engine[Google GKE] is a pre-built Kubernetes cluster offered by the cloud provider https://cloud.google.com/gcp[Google Cloud Platform (GCP)].

You can create a GKE Cluster in GCP for installing using Nuvolaris using xref:download.adoc[nuv] as follows:

. install the <<install-cli, GCloud CLI>>
. <<configure, configure GKE>>
. <<provision, provision GKE>>
. optionally, retrieve the <<retrieve-lb, load balancer address>> to configure a DNS name

Once you have GKE up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the GCloud CLI

Our cli `nuv` uses under the hood the https://cloud.google.com/sdk/gcloud[GCloud CLI version 2], so you need to dowload and install it https://cloud.google.com/sdk/docs/install[following those instructions].

Once installed, ensure it is available on the terminal executing the following command:

----
aws --version
----

you should receive something like this:

====
`aws-cli/2.9.4 Python/3.9.11 Linux/5.19.0-1025-aws exe/x86_64.ubuntu.22 prompt/off`
====



[#get-credentials]
== Login in GCloud

[#configure]
== Configuring GKE

---
nuv config gke
---

[#provision]
== Provisioning GKE

----
nuv cloud gke create
----

[#retrieve-lb]
== Retrieve the Load Balancer Address

----
nuv cloud gke lb
----

== Additional Commands

* `nuv cloud gke delete`
* `nuv cloud gke kubeconfig`
