== Installing Nuvolaris in a Linux Server

You can install Nuvolaris in any server either in your intranet on in Internet running a Linux distribution.

The requirements are:

. The server requires at least 8GB of memory and 30GB of disk space available.
. It should be running a Linux distribution https://docs.k3s.io/installation/requirements[supported by K3S].
. You must open the firewall to access the ports 80, 443 and 6443 from your your machine. 
. You have to install a <<sshkey, public ssh key>> to access to it without a password.
. You have to configure <<sudo, sudo>> to execute root comands without a password.

For informations, how to open the firewall, please consult documentation of your cloud provider to know how to do it, as there are no common procedures.

Read below for information how to create a <<sshkey, sshkey>> and <<sudo, configure sudo>>

[#sshkey]
== Installing a Public SSH key

To connect to a server without a password using `openssh` you need a couple of file called **ssh keys**.

You can generate them on command line using this command:

----
ssh-keygen
----

It will create a couple of files, typically called:

* ~/.ssh/id_rsa
* ~/.ssh/id_rsa.pub

where `~` is your home directory.

You have to keep secret the `id_rsa` file, because it is the private key. You can copy the `id_rsa.pub` in the server or even share it publicly, as it is the public key.

Once you have generated the public key, access to your server and edit the file `~/.ssh/authorized_keys` and add the public key to it (it is just one line, contained in the `id_rsa.pub` file).  

Create the file if it does not exist and do not remove 
other lines if you do not want to remove access to others.

[#sudo]
== Configure SUDO

You normalyl access to Linux servers using an user that is *not* `root` (the system administrator). It depends on the  system, it can be `ubuntu`, `ec2-user`, `admin` or others.

But you need to give to this user the right to execute commands as `root` without a password, and you do this configuring the command `sudo`.

You usally have either access to root with the `su` command, or you can execute `sudo` with a password.

Type either `su` or `sudo bash` to become root and edit the file `/etc/sudoers` adding the following line:

----
<user> ALL=(ALL) NOPASSWD:ALL
----
 