== Installing Nuvolaris in a Linux Server

You can install Nuvolaris in any server either in your intranet on in Internet running a Linux distribution.

The requirements are:

. The server requires at least 8GB of memory and 30GB of disk space available.
. It should be running a Linux distribution https://docs.k3s.io/installation/requirements[supported by K3S].
. You must open the firewall to access the ports 80, 443 and 6443 from your your machine. 
. You have to install a <<sshkey, public ssh key>> to access to it without a password.
. You have to configure <<sudo, sudo>> to execute root comands without a password.

For informations, how to open the firewall, please consult documentation of your cloud provider to know how to do it, as there are no common procedures.

Read below for information how to create a <<sshkey, sshkey>> and <<sudo, configure sudo>>

[#sshkey]
== Installing Public SSH key

== Generate an SSH key

To connect to a server you need a couple of file called **ssh keys**

You can generate them on command line using

----
ssh-keygen
----

It will create a couple of files, typically called:

* ~/.ssh/id_rsa
* ~/.ssh/id_rsa.pub

You have to keep secret the `id_rsa` file, while you can copy the `id_rsa.pub` file and install in the server to access it.


[#sudo]
== Configure SUDO
* ti give sudo rights to a non-root user, usually you need to use the root password, then edit the file /etc/sudoers and add the line:

----
<user> ALL=(ALL) NOPASSWD:ALL
----

== Generic instructions.

The generic instructions are the following:

* Usually you will be given an IP address and a password.
* Using those informations you will be able to enter in the server, edit the file `~/.ssh/authorized_keys` and  add your `id_rsa.pub` 
* if you are using a non-root user, ensure this user has the right to use `sudo` to run commands as a root without a password. 

(change `<user>` with your actual user).


See xref:server-generic.adoc[here] for informations how to install it in a server.
 
