= Install K3S in a server

You can install Nuvolaris as xref:install-server.adoc[describe here] and you do not need to install any Kubernetes in it, as it is installed as part of the procedure. In this case it installs https://k3s.io[K3S].

Or you can <<install-k3s, install K3S in advance>>, and then proceed xref:install-cluster.adoc[installing as in any other Kubernetes cluster].

[#installing-k3s]
== Installing K3S in a server

Before installing ensure you have xref:prereq-server.adoc[satified the prerequisites], most notably:

. you server operating system satisfies the https://docs.k3s.io/installation/requirements[K3S requiements]
. you have passwordless access with ssh
. you have an user with passwordless sudo rights
. you have opened the port 6443 in the firewall

Then you can use the following subcommand to install in the server:

----
nuv cloud k3s create SERVER=<server> USERNAME=<usernam>
----

where `<server>` is the internet address or name to access the server, and `<username>` is the user you use to access the server.

Those informations should have been provided when provisioning the server.

[IMPORTANT]
====
If you installed a Kubernetes cluster in the server in this way, you should proceed installing Nuvolars as in xref:install-cluster.adoc[a Kubernetes cluster],  **not** as a server.
====

The installation retrieves also a kubernets configuration file so you can proceed to installing it without any other step involved.

== Additional Commands

In addition to `create` you have available also the following subcommands:

* `nuv cloud k3s delete SERVER=<server> USERNAME=<username>`: uninstall K3S from the server
* `nuv cloud k3s kubeconfig SERVER=<server> USERNAME=<username>`: retrieve the kubeconfig from the K3S server
* `nuv cloud k3s info`: informations about the server
* `nuv cloud k3s status`: status of the server

