
== Installing Public SSH key

Once you got your `id_rsa.pub` and a server, get access to it.

The exact instructions depends on the specific provider.

== Generic instructions.

The generic instructions are the following:

* Usually you will be given an IP address and a password.
* Using those informations you will be able to enter in the server, edit the file `~/.ssh/authorized_keys` and  add your `id_rsa.pub` 
* if you are using a non-root user, ensure this user has the right to use `sudo` to run commands as a root without a password. 
* ti give sudo rights to a non-root user, usually you need to use the root password, then edit the file /etc/sudoers and add the line:

----
<user> ALL=(ALL) NOPASSWD:ALL
----

(change `<user>` with your actual user).


== Generate an SSH key

To connect to a server you need a couple of file called **ssh keys**

You can generate them on command line using

----
ssh-keygen
----

It will create a couple of files, typically called:

* ~/.ssh/id_rsa
* ~/.ssh/id_rsa.pub

You have to keep secret the `id_rsa` file, while you can copy the `id_rsa.pub` file and install in the server to access it.

See xref:server-generic.adoc[here] for informations how to install it in a server.
 
