= Provision a server in Amazon Web Services

https://aws.amazon.com/eks/[Amazon EKS] is a pre-built Kubernetes cluster offered by the cloud provider https://aws.amazon.com/[Amazon Web Services].

You can create an EKS Cluster in Amazon AWS for installing using Nuvolaris using xref:download.adoc[nuv] as follows:

. install `aws`, the <<install-cli, AWS CLI>>
. get <<get-credentials, Access and Secret Key>>
. <<configure, configure EKS>>
. <<provision, provision EKS>>
. optionally, retrieve the <<retrieve-lb, load balancer address>> to configure a DNS name

Once you have EKS up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the AWS CLI

Our cli `nuv` uses under the hood the https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[AWS CLI version 2], so you need to dowload and install it https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[following those instructions].

Once installed, ensure it is available on the terminal executing the following command:

----
aws --version
----

you should receive something like this:

====
`aws-cli/2.9.4 Python/3.9.11 Linux/5.19.0-1025-aws exe/x86_64.ubuntu.22 prompt/off`
====

Ensure the version is at least 2.

[#get-credentials]
== Getting the Access and Secret key

:create-keys: https://repost.aws/knowledge-center/create-access-key
:eksctl-permissions: https://eksctl.io/usage/minimum-iam-policies/
 
Next step is to retrieve credentials, in the form of an access key and a secret key.

So you need to: 
* access the AWS console  {create-keys}[following those instructions] create an access key and secret key,  
* give to the credentials the minimum required permissions  {eksctl-permissions}[as described here] to build an EKS cluster.

You will end up with a couple of string as follows:

====
Sample AWS Access Key ID: AKIAIOSFODNN7EXAMPLE
Sample AWS Secret Access Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
====

Take note of them as you need them for configuring out CLI.

[#configure]
== Configuring Amazon EKS
