== Prerequisites

This page lists the prerequisites to install Nuvolaris in the various environments.

For **development** purposes, you can install a single node Nuvolaris deployment in the following enviroments.

* Install in your xref:install-local.adoc[local machine]:
** you need xref:prereq-docker.adoc[Docker Desktop] 
* Install in a *single node* xref:install-server.adoc[Linux server]: 
** you need a xref:prereq-server.adoc[Linux server]  accessible with SSH

Our installer automatically installs https://k3s.io.[K3S], but if you prefer you can preinstall a single node Kubernetes nstances. If you choose to install 

* If you choose to install Kubernetes in your cluster, you need to install either:
** xref:prereq-k3s.adoc[SuSE K3S] 
** xref:prereq-mk8s.adoc[Canonical MicroK8S]

For **production** purposes, you can install a multi-node Nuvolaris deployment in any xref:install-cluster.adoc[Kubernetes cluster] accessible with its `kubeconfig` file as long the cluster satifies xref:prereq-generic.adoc[some requirements].

We support installing Nuvolaris in the following  Kubernetes environments:

* xref:prereq-eks.adoc[EKS in Amazon AWS] 
* xref:prereq-aks.adoc[AKS in Microsoft Azure]
* xref:prereq-gke.adoc[GKE in Google Cloud]
* xref:prereq-osh.adoc[RedHat OpenShift in supported cloud] 
