== Prerequisites

This page lists the prerequisites to install Nuvolaris in the various environments.

=== Single Node development installation

For **development** purposes, you can install a single node Nuvolaris deployment in the following enviroments.

* Install in your xref:install-local.adoc[local machine]:
** you need xref:prereq-docker.adoc[Docker Desktop] 
* Install in a *single node* xref:install-server.adoc[Linux server]: 
** you need a xref:prereq-server.adoc[Linux server]  accessible with SSH

Our installer automatically installs https://k3s.io[K3S], but if you prefer you can preinstall a single node Kubernetes nstances. 

* If you choose to install Kubernetes in your server, we provide support for:
** xref:prereq-k3s.adoc[SuSE K3S] 
** xref:prereq-mk8s.adoc[Canonical MicroK8S]

=== Multi Node production installation

For **production** purposes, need a multi-node Kubernetes cluster which satifies xref:prereq-generic.adoc[some requirements], accessible with its `kubeconfig` file.

If you have such a cluster, you can perform a xref:install-cluster.adoc[Nuvolaris Kubernetes cluster]

We provide support for configuring the following  Kubernetes environments:

* xref:prereq-eks.adoc[EKS in Amazon AWS] 
* xref:prereq-aks.adoc[AKS in Microsoft Azure]
* xref:prereq-gke.adoc[GKE in Google Cloud]
* xref:prereq-osh.adoc[RedHat OpenShift] 

After you have satisfied the prerequisites, you can proceed xref:install.adoc[installing Nuvolaris].