= Prerequisites to install Nuvolaris in RedHat OpenShift

https://www.redhat.com/en/technologies/cloud-computing/openshift[RedHat OpenShift] is a Kubernetes distribution offered by https://www.redhat.com[RedHat], a division of IBM.


OpenShift is available in a variety of cloud environment and provider, https://github.com/openshift/installer[using its own installer]

You can xref:install-cluster[install Nuvolaris in OpenShift], provided you have already installed OpenShift.

The procedure is the following:

. Install OpenShift in any supported environment https://docs.openshift.com/container-platform/4.13/installing/index.html[following this guide]

. At the end of the installation, the installer  will leave a `kubeconfig` file in a folder. You need to import it with the command:

----
nuv cloud osh import <kubeconfig>
----

where `<kubeconfig>` is the path to the generated `kubeconfig`

. Setup the required components (currently, `acme-openshift`) with 

---- 
nuv cloud config setup
----

Once you have OpenShift up and running and you imported its kubeconfig you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

