= Prerequisites to install Nuvolaris in an Amazon EKS Cluster

https://aws.amazon.com/eks/[Amazon EKS] is a pre-built Kubernetes cluster offered by the cloud provider https://aws.amazon.com/[Amazon Web Services].

You can create an EKS Cluster in Amazon AWS for installing using Nuvolaris using xref:download.adoc[nuv] as follows:

. install the <<install-cli, AWS CLI>>
. get <<get-credentials, Access and Secret Key>>
. <<configure, configure EKS>>
. <<provision, provision EKS>>
. optionally, retrieve the <<retrieve-lb, load balancer address>> to configure a DNS name

Once you have EKS up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the AWS CLI

Our cli `nuv` uses under the hood the https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[AWS CLI version 2], so you need to dowloand and install it https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[following those instructions].

Once installed, ensure it is available on the command line with the following command:


----
aws --version
----

you should receive something like this:

====
`aws-cli/2.9.4 Python/3.9.11 Linux/5.19.0-1025-aws exe/x86_64.ubuntu.22 prompt/off``
====

Ensure the version is at least 2.

[#get-credentials]
== Getting the Access and Secret key

:create-keys: https://repost.aws/knowledge-center/create-access-key
:eksctl-permissions: https://eksctl.io/usage/minimum-iam-policies/
 
Before starting, you need to: 
* retrieve access the AWS console and {create-keys}[create an access key and secret key],  
* give to the user the minimum required permissions  {eksctl-permissions}[as described here] to build an EKS cluster.

You will end up with a couple of string as follows:

====
Sample AWS Access Key ID: AKIAIOSFODNN7EXAMPLE
Sample AWS Secret Access Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
====

Take note of them as you need them for configuring out CLI.

[#configure]
== Configuring Amazon EKS

Once you have the access and secret key you can configure EKS with the command `nuv config eks` answering to all the questions, as in the following example:

----
$ nuv config eks
*** Please, specify AWS Access Id and press enter.
AKIAIOSFODNN7EXAMPLE
*** Please, specify AWS Secret Key and press enter.
wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
*** Please, specify AWS Region to use and press enter.
To get a list of valid values use:
  aws ec2 describe-regions --output table

Just press enter for default [us-east-2]: 

*** Please, specify AWS public SSH key  and press enter.
If you already have a public SSH key in AWS, provide its name here.
If you do not have it, generate a key pair with the following command:
  ssh-keygen
The public key defaults to ~/.ssh/id_rsa.pub and you can import with:
  aws ec2 import-key-pair --key-name nuvolaris-key --public-key-material --region=<your-region> fileb://~/.ssh/id_rsa.pub

Just press enter for default [nuvolaris-key]: 

*** Please, specify EKS Name for Cluster and Node Group and press enter.
Just press enter for default [nuvolaris]: 

*** Please, specify EKS region and press enter.
To get a list of valid values use:
  aws ec2 describe-regions --output table

Just press enter for default [us-east-1]: 

*** Please, specify EKS number of worker nodes and press enter.
Just press enter for default [3]: 

*** Please, specify EKS virtual machine type and press enter.
To get a list of valid values, use:
  aws ec2 describe-instance-types --query 'InstanceTypes[].InstanceType' --output table 

Just press enter for default [m5.xlarge]: 

*** Please, specify EKS disk size in gigabyte and press enter.
Just press enter for default [50]: 

*** Please, specify EKS Kubernetes Version and press enter.
Just press enter for default [1.25]: 

EKS_KUBERNETES_VERSION=1.25
EKS_NAME=nuvolaris
EKS_REGION=us-east-1
EKS_VM=m5.xlarge
EKS_DISK=50
EKS_COUNT=3
----

[#provision]
== Provisioning Amazon EKS

----
nuv cloud eks create
----

[#retrieve-lb]
== Provisioning Amazon EKS

== Additional Commands

* `nuv cloud eks delete`
* `nuv cloud eks kubeconfig`
* `nuv cloud eks lb`
