= Prerequisites to install Nuvolaris in an Azure AKS Cluster

https://aws.amazon.com/eks/[Azure AKS] is a pre-built Kubernetes cluster offered by the cloud provider https://azure.microsoft.com/[Microsoft Azure].

You can create an AKS Cluster in Microsoft Azure for installing using Nuvolaris using xref:download.adoc[nuv] as follows:

. install `az`, the <<install-cli, Azure CLI>>
. <<configure, configure AKS>>
. <<provision, provision AKS>>
. optionally, retrieve the <<retrieve-lb, load balancer address>> to configure a DNS name

Once you have AKS up and running you can proceed xref:configure.adoc[configuring] and xref:install-cluster.adoc[installing Nuvolaris].

[#install-cli]
== Installing the Azure CLI

Our CLI `nuv` uses under the hood the https://learn.microsoft.com/en-us/cli/azure/[Azure CLI], so you need to dowload and install it https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[following those instructions].



[#configure]
== Configuring Azure AKS

---
nuv config aks
---

[#provision]
== Provisioning Azure AKS

----
nuv cloud aks create
----

[#retrieve-lb]
== Provisioning Amazon EKS

----
nuv cloud aks lb
----

== Additional Commands

* `nuv cloud aks delete`
* `nuv cloud aks kubeconfig`
