= Quick Start

This is a quick start guide to the installation process, omitting a lot of details. You can use this if you are experienced and come back to the documentation when something does not work properly.

== Prerequisites

First, xref:download.adoc[download our CLI `nuv`] picking the version suitable for your environment. We support only 64 bit versions of recent Windows, MacOS and Linux os/distributions. 

Second, configure the services you want to enable. By defalt Nuvolaris will install only the serverless engine with no services enabled. If you want to enable all of them, use:

----
nuv config enable --all
----

otherwise pick the services you want, among `--redis`, `--mongodb`, `--minio`, `--cron`, `--postgres`. Note that `--mongodb` is actually https://www.ferretdb.io[FerretDB] and requires Postgres that is implicitly also enabled. More details xref:configure.adoc[here]. 

Now, pick a suitable environment and install Nuvolaris.

== Local Install

If you have a decent machine with at least 16GB of memory running a 64bit recente operationg system and you do now want to use any server or cloud, install 
https://www.docker.com/products/docker-desktop/[Docker Desktop].

Once you have installed the CLI and configured you services, you can install Nuvolaris and its services in Docker with:

----
nuv setup devcluster
----

Once it is installed, you can proceed to read the xref:tutorial:index.adoc[ tutorial].

== Server Install

If you have root access to Linux Server with at least 8GB of memory, you can install a suitable Kubernetes cluster

 available, with at , configure it to access with ssh without a password, using `authorized_keys` and ensure the user you are using 

== Configure

By default you will install only the serverless engine, using the http protocol and no additional services.

If you want to enable additional services, you need to enable  them. You can enable all of them

== Local Install



`nuv setup devcluster`

== Linux Install

If you have a Linux server
