= Quick Start

This is a quick start guide to the installation process, omitting a lot of details. You can use this if you are experienced and come back to the documentation when something does not work properly.

== Prerequisites

First, xref:download.adoc[download `nuv`], the Nuvolaris CLI, the version suitable for your environment. We support the 64 bit version of recent Windows, MacOS and major Linux distributions.

Second, configure the services you want to enable. By defalt Nuvolaris will install only the serverless engine with no services enabled. If you want to enable all of them, use:

----
nuv config enable --all
----

otherwise pick the services you want, among `--redis`, `--mongodb`, `--minio`, `--cron`, `--postgres`. Note that `--mongodb` is actually https://www.ferretdb.io[FerretDB] and requires Postgres that is implicitly also enabled. More details xref:configure.adoc[here]. 

Now, choose where to install Nuvolaris. 

Your options are:

* <<locally,locally>> in your workstation;
* in a Linux <<server,server>> you have `root` access with `ssh`
* in a Kubernets <<cluster,cluster>> you have `cluster-admin` access to it with `kubectl`
* in <<cloud,cloud>>, where you can provision a Kubernetes cluster 

[#locally]
== Local Install

If you have a *decent* workstation (with at least 16GB of memory) running a  *recent*  and **64 bit** operating system and you do now want to use any server or cloud, install 
https://www.docker.com/products/docker-desktop/[Docker Desktop].

Once you have installed the CLI and configured you services, you can install Nuvolaris and its services in Docker with:

----
nuv setup devcluster
----

Once it is installed, you can proceed to read the xref:tutorial:index.adoc[tutorial].

[#server-dns]
== Server DNS


[#server-install]
== Server Install

If you have `root` access to Linux server with at least 8GB of memory and 30GB of space, you can install Nuvolaris directly in it. 

The server can be physical or virtual. We need Kubernetes in it but the installer takes care of installing also a flavor of Kubernetes, https://k3s.io[K3S].


[#cloud]
== Cloud Install


[#cluster]
== Cluster Install
If you have access to a Kubernetes cluster with `cluster-admin` role you can install Nuvolaris in it.


