= Quick Start

This is a quick start guide to the installation process, omitting a lot of details. You can use this if you are experienced and come back to the documentation when something does not work properly.

== Prerequisites

First, xref:download.adoc[download `nuv`], the Nuvolaris CLI, the version suitable for your environment. We support the 64 bit version of recent Windows, MacOS and major Linux distributions.

Second, configure the services you want to enable. By defalt Nuvolaris will install only the serverless engine with no services enabled. If you want to enable all of them, use:

----
nuv config enable --all
----

otherwise pick the services you want, among `--redis`, `--mongodb`, `--minio`, `--cron`, `--postgres`. Note that `--mongodb` is actually https://www.ferretdb.io[FerretDB] and requires Postgres that is implicitly also enabled. More details xref:configure.adoc[here]. 

Now, choose where to install Nuvolaris. 

Your options are:

* <<locally,locally>> in your workstation;
* in a Linux <<server,server>> in your intranet
* in a Linux <<internet-server,server>> available on Internet
* in a Kubernets <<cluster,cluster>> in your intranet
* in <<cloud-cluster,cloud>>, where you can provision a Kubernetes cluster 

[#locally]
== Local Installtion

If you have a *decent* workstation (with at least 16GB of memory) running a  *recent*  and **64 bit** operating system, you can install 
https://www.docker.com/products/docker-desktop/[Docker Desktop] and then install Nuvolaris in it.

Once you have: 
. installed the CLI a
. configured you services 
. installed Docker Desktop

you can install Nuvolaris and its services in Docker with just:

----
nuv setup devcluster
----

Once it is installed, you can proceed to read the xref:tutorial:index.adoc[tutorial].

[#internet-server]
== Internet Server Configuration

If you have access to server on Internet, you will get an IP address to reach it.

Many cloud providers also gives you a DNS name, that can be very ugly as  `ec2-12-34-56-78.us-west-2.compute.amazonaws.com`, but nonetheles is better than just the IP addres and should be used

[#server]
== Server Installation

If you have access to a Linux server, with:
. an IP address or DNS name, referred as `<server>`
. at least 8GB of memory and 50GB of disk space available
. passwordless access with `ssh` to a Linux user `<user>`
. the user `<user>` has passwordless `sudo` rights
. the firewall allows traffic to the  ports 80, 443 and 6443

then you can install Nuvolaris in it.

The server can be physical or virtual. We need Kubernetes in it but the installer takes care of installing also a flavor of Kubernetes, https://k3s.io[K3S], courtesy of https://github.com/alexellis/k3sup[K3Sup]


[IMPORTANT]
====
Replace in the following command `<server>`  with the address of your server, and `<user>` with the actual user to use in your server.
====

To install Nuvolaris, first check you have access to the server with:

----
ssh <user>@<server> sudo hostname
----

If you do not receive errors, you can install Nuvolaris with: 

----
nuv setup server <server> <user>
----


[#cloud-cluster]
== Cloud Cluster Provisioning


[#cluster]
== Cluster Install

If you have access to a Kubernetes cluster with `cluster-admin` role you can install Nuvolaris in it.


