= Welcome to MastroGPT

== Intro

MastroGPT is a product of Nuvolaris that enables the creation of your own artificial intelligence applications. The environment is connected to both the OpenAI API and the Nuv platform.

With MastroGPT, you can deploy your software based on nuv entities(packages, actions, activations ...). 
Currently, we offer support for Python, Node.js, Java, Go, and JavaScript runtimes. You can choose your preferred language and build your own AI application.

== How to Start

As for the frontend, you have the option to use pure HTML/CSS/JS or a single-page application framework such as React, Angular, or Svelte (after building it with npm run build or similar).

The unique constraint is to place backend code under the `/packages` folder and frontend code under the `/web` folder. 
We'll explain better this on xref:environment.adoc[Enviroment]

MastroGPT, as mentioned earlier, offers developers everything they need to build their own applications, with specific integrations for AI and major cloud providers, a dedicated user interface, and a scalable serverless platform. In particular, direct access to OpenAI is provided (each environment has its own specific key) and is integrated seamlessly.

=== Getting Started with GitHub

If you're new to the product and want to start with some examples to better understand it, you can visit https://github.com/mastrogpt and choose between starter templates or demo repositories. For example, you can explore the python-starter repository (https://github.com/mastrogpt/python-starter).

If you already have a Nuvolaris namespace registered, you can instantly start using this repository with GitHub Codespaces! Once the development container is built, you'll be prompted to enter your Nuvolaris username and password via the CLI. To see this starter template in action, simply run the command `task devel` on the integrated Codespaces CLI. Visual Studio Code's browser will prompt you to open the application in a specific port, and your starter template will be ready to run!

=== Start from Admin




